packages:
  - packages/*

allowBuilds:
  '@swc/core': true
  esbuild: true

catalog:
  '@biomejs/biome': ^2.5.7
  '@swc/core': ^1.15.47
  '@types/node': ^26.1.2
  '@vitest/ui': ^4.1.10
  tsx: ^4.23.9
  turbo: ^2.10.8
  vitest: ^4.1.10

catalogMode: prefer

supportedArchitectures:
  cpu: [ current ]
  os: [ current ]
