packages:
  - packages/*

allowBuilds:
  '@swc/core': true
  esbuild: true

catalog:
  '@biomejs/biome': ^2.5.15
  '@swc/core': ^1.16.13
  '@types/node': ^26.6.4
  '@vitest/ui': ^5.0.3
  tsx: ^4.23.15
  turbo: ^2.11.7
  vitest: ^5.0.3

catalogMode: prefer

supportedArchitectures:
  cpu: [ current ]
  os: [ current ]
