packages:
  - packages/*

allowBuilds:
  '@swc/core': true
  esbuild: true

catalog:
  '@biomejs/biome': ^2.5.2
  '@types/node': ^26.1.0
  tsx: ^4.23.0
  turbo: ^2.10.3

catalogMode: prefer

supportedArchitectures:
  cpu: [ current ]
  os: [ current ]
